---

- name: Install misc packages
  package:
    name: "{{ item }}"
    state: latest
  with_items:
    "{{ basic_packages }}"

- name: Install pip packages
  pip:
    name: "{{ item }}"
    state: latest
  with_items:
    "{{ pip_packages }}"

- name: Include AWS udev tasks
  include_tasks: 'tasks/aws-udev.yml'